export const quotes = [
  "Neon raindrops taste like static electricity",
  "Gravity isn’t broken, just indecisive today",
  "The AI kept laughing at a joke it never told me",
  "Portals keep opening where I misplace my wallet",
  "The city hums secrets beneath the streetlights",
  "Spartan armor feels heavier on Thursdays",
  "Deckard insists the unicorn was definitely real",
  "The cake emailed me about unresolved trust issues",
  "Bananas staged a tiny coup at midnight",
  "The spoon bent itself just to show off",
  "Glitches sound like old radio static dreaming",
  "I swear the shadows whispered my name",
  "Timelines sometimes forget their own order",
  "Old gods binge-watch humanity before breakfast",
  "Elevators shouldn’t know personal details",
  "Neo keeps debugging the déjà vu anomaly",
  "Cortana murmured something about destiny diverging",
  "I tried to jump but reality rejected the request",
  "Pixels flickered like they were gossiping",
  "My reflection keeps looking the wrong way",
  "The moon rebooted while no one was watching",
  "NPCs are starting to ask strange questions",
  "The void politely ignored me again",
  "This universe definitely runs on bad timing",
  "Someone rewrote gravity’s rules for fun",
  "A hologram winked and corrupted itself instantly",
  "I heard a glitch laugh under its breath",
  "The sky updated without patch notes",
  "Dreams are just low-resolution prophecies",
  "The soup stared back and blinked",
  "Time folded like cheap paper",
  "My shadow arrived five seconds early",
  "The portal told me I wasn’t authorized",
  "Someone installed sarcasm into the weather",
  "Thunder spoke fluent binary last night",
  "I’m fairly sure the mirror lied again",
  "The universe skipped a frame on purpose",
  "Someone muted reality for a moment",
  "My thoughts lagged during conversation",
  "A neon sign declared itself sentient",
  "The AI requested a vacation from humanity",
  "Static hummed a familiar lullaby",
  "The city lights argued over brightness levels",
  "A glitch tried to shake my hand",
  "The clouds glitched into pixel art",
  "My shoes refused to walk straight today",
  "Someone stole the color blue for an hour",
  "The vending machine offered life advice",
  "I saw a hologram sneeze",
  "Stars flickered like faulty LEDs",
  "The wind whispered debugging errors",
  "The ceiling tried to close its eyes",
  "Numbers fell out of the clock",
  "I found a message written in static",
  "A shadow tripped over itself",
  "Time coughed awkwardly",
  "The data stream felt suspiciously warm",
  "The planet sighed again",
  "My dreams updated overnight",
  "The walls hummed a familiar tune",
  "The signal asked me to wait",
  "Color bled from the horizon",
  "Reality lagged but refused to restart",

  "I'm Batman.",
  "I am vengeance.",
  "I am the night.",
  "Fear is a tool.",
  "I wear the mask. The mask doesn’t wear me.",
  "A hero can be anyone.",
  "Justice is silence before it strikes.",
  "I won't kill you, but I don't have to save you.",
  "Some men just want to watch the world burn.",
  "You either die a hero or live long enough to become the villain.",
  "It's what I do that defines me.",
  "Swear to me!",
  "You’re not the devil. You’re just practice.",
  "Sometimes the truth isn’t good enough.",
  "Not everything. Just the things that matter.",
  "Bats frighten me. My enemies should feel the same fear.",
  "I have one power: never giving up.",
  "Gotham needs something more than a man.",
  "Pain is the first lesson. The second is purpose.",
  "The night listens even when no one else does.",
  "No guns. That’s the rule.",
  "I fight so others won’t have to.",
  "Darkness is only dangerous when you forget the light.",
  "Hope can be sharp as a batarang.",
  "I keep falling so I can rise again.",
  "Every scar is a story Gotham doesn’t need to hear.",
  "The shadows follow me because they trust me.",
  "Villains rise when good men look away.",
  "Fear shapes the path I walk.",
  "The mask protects more than my face.",
  "Courage grows where fear refuses to die.",
  "Justice walks even when I crawl.",
  "I step into darkness so others see the light.",
  "The city breathes through its silence.",
  "I don’t chase criminals. I hunt them.",
  "A symbol can survive where a man cannot.",
  "Not all wars are fought in daylight.",
  "I live in the moments no one wants to remember.",
  "The night is my ally, not my escape.",
  "Shadows reveal truths the sun hides.",
  "Crime sleeps when fear wakes up.",
  "I don't need superpowers. I need purpose.",
  "Vengeance taught me discipline.",
  "The cape is a reminder to never fall the same way twice.",
  "My voice isn’t loud. It doesn’t need to be.",
  "Gotham breaks, but I bend with it.",
  "Pain sharpened me into something useful.",
  "Criminals fear what they can’t predict.",
  "I walk where others hesitate.",
  "Every villain thinks they're the exception.",
  "The city remembers every choice I make."
];